### ISSUE TITLE
Wrestic Ignores Config File

### ISSUE THREAD

**Issue by Mrs-Feathers** [alvaro17f/wrestic#2]
Hello!

I installed via this command:
root@backup:~# curl -sL $(curl -s https://api.github.com/repos/alvaro17f/wrestic/releases/latest | grep browser_download_url | cut -d '"' -f 4) | sudo tar zxf - -C /usr/bin --overwrite

install was successful and then i made the config in   /root/.config/wrestic/wrestic.toml  
filled with 
[settings.local]
BACKEND = "local"
RESTIC_PASSWORD = "notrealpassword"
REPOSITORY = "/mnt/backups/"
BACKUP_FOLDER = "/mnt/datastore/"
RESTORE_FOLDER = "/root/restored"
KEEP_LAST = 10

but wrestic doesn't seem to find it. command "wrestic" run from home dir gives output:

✔ WRESTIC · Snapshots
Error: Failed to find config file

but the config file is put in the place i was told to place it in the documentation. is there something wrong or is the documentation out of date and the config file is moved?

**Comment by badwatt** [comment]
Thank you @Mrs-Feathers for opening this issue, it has been fixed in version 1.3.
You can run `sudo wrestic update` to get the latest version and check.
