### ISSUE TITLE
not all commands require root

### ISSUE THREAD

**Issue by tippfehlr** [alvaro17f/wrestic#3]
Hi, I’d like to package this for the AUR.
Would it be possible to generate the shell files without root?
Not every command needs root, and running `wrestic --help` should also work without root.

**Comment by badwatt** [comment]
Hi @tippfehlr,
You're right, I want to improve this, but at this moment I don't have the time.
In a near future I'll be deploying a new version with this improvement. I have been already working on this.
It would be great to see Wrestic on AUR.

EDIT: I've just seen that you've already packaged It for AUR, thank you.

**Comment by tippfehlr** [comment]
Take your time :)

> I've just seen that you've already packaged It for AUR, thank you.

Yes, without shell completions for now.

**Comment by badwatt** [comment]
Good news!

@tippfehlr sudo has been removed for version 1.5.0.
You'll be prompted if needed.

Talking about completions, fish has been added.
For bash, now completions are stored inside home (just like fish).
Not yet for zsh, but you'll be prompted as well.

Thank you!

**Comment by tippfehlr** [comment]
Thanks!
I hope you don’t mind that I’ve submitted another solution for completions in #6. I think it is more standard (used by rustup, for example) than your version and is easier to use in scripts.
[Here](https://github.com/rust-lang/rustup/blob/9955b9f889889a495b380e73709db5480c6a656b/doc/user-guide/src/installation/index.md#enable-tab-completion-for-bash-fish-zsh-or-powershell) is a description how to use `wrestic completions` as a user.

If that’s ok I would like to wait for #5 and #6 to be merged before releasing it.

**Comment by tippfehlr** [comment]
@alvaro17f I don’t know if GitHub sends notifications for closed PRs ^^
